name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Box
        - Button
        - Input
        - Dialog
        - Avatar
        - Chip
        - Slider
        - Toggle
        - Other
        - Multiple components
    validations:
      required: true

  - type: dropdown
    id: variant
    attributes:
      label: Variant
      description: Which variant of the library are you using?
      options:
        - Core (default)
        - Tailwind
        - Stylesheet
        - Hybrid
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Please provide a minimal code sample that reproduces the issue.
      render: typescript
      placeholder: |
        ```tsx
        import { Box } from 'chill-ui';
        
        export default function MyComponent() {
          return (
            <Box>
              {/* Your code here */}
            </Box>
          );
        }
        ```

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g. iOS, Android, Web]
        - React Native version: [e.g. 0.72.0]
        - Chill UI version: [e.g. 1.0.0]
        - Device: [e.g. iPhone 14, Pixel 6]

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Screenshots, error messages, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues before creating this one
          required: true
        - label: I have provided a minimal code sample that reproduces the issue
          required: true
        - label: I have provided environment details
          required: true
