name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: dropdown
    id: component
    attributes:
      label: Component/Area
      description: Which component or area would this feature affect?
      options:
        - New Component
        - Box
        - Button
        - Input
        - Dialog
        - Avatar
        - Chip
        - Slider
        - Toggle
        - Core Library
        - Build System
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be useful
        - High - Important for my use case
        - Critical - Blocking my project
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        I'm always frustrated when...
        This would help me because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: |
        I would like to see...
        The ideal solution would...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or workarounds you've considered.
      placeholder: |
        I've tried...
        As a workaround, I...

  - type: textarea
    id: api
    attributes:
      label: Proposed API
      description: If applicable, describe how you envision the API for this feature.
      render: typescript
      placeholder: |
        ```tsx
        // Example usage
        import { NewComponent } from 'chill-ui';
        
        <NewComponent 
          prop1="value"
          prop2={true}
          onAction={(value) => console.log(value)}
        />
        ```

  - type: textarea
    id: examples
    attributes:
      label: Real-world Examples
      description: Provide examples of similar features in other libraries or applications.
      placeholder: |
        - Library X has this feature...
        - App Y implements this by...
        - This is similar to...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here.
      placeholder: Screenshots, mockups, links to similar implementations, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests before creating this one
          required: true
        - label: I have provided a clear problem statement and proposed solution
          required: true
        - label: I have considered alternative solutions
          required: true
