import type { Meta, StoryObj } from '@storybook/react-native-web-vite';

import UiPresentation from './storybook';
import { PhoneNumberInput } from '../src/components';

const meta: Meta<typeof PhoneNumberInput> = {
  args: {
    defaultCountry: 'FR',
    defaultErrorMessage: 'the phone number is invalid',
    defaultLanguage: 'en',
    defaultOpen: false,
    dropdownPosition: 'auto',
    dropdownProps: { hasSearch: true },
    hasErrorOnChange: true,
    inputPlaceholder: 'Enter your phone number',
    inputSearchPlaceholder: 'Search a country...',
    itemAsClickable: 'touchable-opacity',
    language: 'en',
    maxHeight: 340,
    minHeight: 0,
    offsetY: 5,
  },
  argTypes: {
    allowedCountries: {
      control: {
        type: 'multi-select',
      },
      options: [
        'AF',
        'AX',
        'AL',
        'DZ',
        'AS',
        'AD',
        'AO',
        'AI',
        'AQ',
        'AG',
        'AR',
        'AM',
        'AW',
        'AU',
        'AT',
        'AZ',
        'BS',
        'BH',
        'BD',
        'BB',
        'BY',
        'BE',
        'BZ',
        'BJ',
        'BM',
        'BT',
        'BO',
        'BA',
        'BW',
        'BR',
        'IO',
        'BN',
        'BG',
        'BF',
        'BI',
        'KH',
        'CM',
        'CA',
        'CV',
        'KY',
        'CF',
        'TD',
        'CL',
        'CN',
        'CX',
        'CC',
        'CO',
        'KM',
        'CG',
        'CD',
        'CK',
        'CR',
        'CI',
        'HR',
        'CU',
        'CY',
        'CZ',
        'DK',
        'DJ',
        'DM',
        'DO',
        'EC',
        'EG',
        'SV',
        'GQ',
        'ER',
        'EE',
        'ET',
        'FK',
        'FO',
        'FJ',
        'FI',
        'FR',
        'GF',
        'PF',
        'GA',
        'GM',
        'GE',
        'DE',
        'GH',
        'GI',
        'GR',
        'GL',
        'GD',
        'GP',
        'GU',
        'GT',
        'GG',
        'GN',
        'GW',
        'GY',
        'HT',
        'VA',
        'HN',
        'HK',
        'HU',
        'IS',
        'IN',
        'ID',
        'IR',
        'IQ',
        'IE',
        'IM',
        'IL',
        'IT',
        'JM',
        'JP',
        'JE',
        'JO',
        'KZ',
        'KE',
        'KI',
        'KP',
        'KR',
        'KW',
        'KG',
        'LA',
        'LV',
        'LB',
        'LS',
        'LR',
        'LY',
        'LI',
        'LT',
        'LU',
        'MO',
        'MK',
        'MG',
        'MW',
        'MY',
        'MV',
        'ML',
        'MT',
        'MH',
        'MQ',
        'MR',
        'MU',
        'YT',
        'MX',
        'FM',
        'MD',
        'MC',
        'MN',
        'ME',
        'MS',
        'MA',
        'MZ',
        'MM',
        'NA',
        'NR',
        'NP',
        'NL',
        'NC',
        'NZ',
        'NI',
        'NE',
        'NG',
        'NU',
        'NF',
        'MP',
        'NO',
        'OM',
        'PK',
        'PW',
        'PS',
        'PA',
        'PG',
        'PY',
        'PE',
        'PH',
        'PN',
        'PL',
        'PT',
        'PR',
        'QA',
        'RO',
        'RU',
        'RW',
        'RE',
        'BL',
        'SH',
        'KN',
        'LC',
        'MF',
        'PM',
        'VC',
        'WS',
        'SM',
        'ST',
        'SA',
        'SN',
        'RS',
        'SC',
        'SL',
        'SG',
        'SK',
        'SI',
        'SB',
        'SO',
        'ZA',
        'SS',
        'ES',
        'LK',
        'SD',
        'SR',
        'SJ',
        'SZ',
        'SE',
        'CH',
        'SY',
        'TW',
        'TJ',
        'TZ',
        'TH',
        'TL',
        'TG',
        'TK',
        'TO',
        'TT',
        'TN',
        'TR',
        'TM',
        'TC',
        'TV',
        'UG',
        'UA',
        'AE',
        'GB',
        'US',
        'UY',
        'UZ',
        'VU',
        'VE',
        'VN',
        'VG',
        'VI',
        'WF',
        'YE',
        'ZM',
        'ZW',
      ],
    },
    defaultCountry: {
      options: [
        'AF',
        'AX',
        'AL',
        'DZ',
        'AS',
        'AD',
        'AO',
        'AI',
        'AQ',
        'AG',
        'AR',
        'AM',
        'AW',
        'AU',
        'AT',
        'AZ',
        'BS',
        'BH',
        'BD',
        'BB',
        'BY',
        'BE',
        'BZ',
        'BJ',
        'BM',
        'BT',
        'BO',
        'BA',
        'BW',
        'BR',
        'IO',
        'BN',
        'BG',
        'BF',
        'BI',
        'KH',
        'CM',
        'CA',
        'CV',
        'KY',
        'CF',
        'TD',
        'CL',
        'CN',
        'CX',
        'CC',
        'CO',
        'KM',
        'CG',
        'CD',
        'CK',
        'CR',
        'CI',
        'HR',
        'CU',
        'CY',
        'CZ',
        'DK',
        'DJ',
        'DM',
        'DO',
        'EC',
        'EG',
        'SV',
        'GQ',
        'ER',
        'EE',
        'ET',
        'FK',
        'FO',
        'FJ',
        'FI',
        'FR',
        'GF',
        'PF',
        'GA',
        'GM',
        'GE',
        'DE',
        'GH',
        'GI',
        'GR',
        'GL',
        'GD',
        'GP',
        'GU',
        'GT',
        'GG',
        'GN',
        'GW',
        'GY',
        'HT',
        'VA',
        'HN',
        'HK',
        'HU',
        'IS',
        'IN',
        'ID',
        'IR',
        'IQ',
        'IE',
        'IM',
        'IL',
        'IT',
        'JM',
        'JP',
        'JE',
        'JO',
        'KZ',
        'KE',
        'KI',
        'KP',
        'KR',
        'KW',
        'KG',
        'LA',
        'LV',
        'LB',
        'LS',
        'LR',
        'LY',
        'LI',
        'LT',
        'LU',
        'MO',
        'MK',
        'MG',
        'MW',
        'MY',
        'MV',
        'ML',
        'MT',
        'MH',
        'MQ',
        'MR',
        'MU',
        'YT',
        'MX',
        'FM',
        'MD',
        'MC',
        'MN',
        'ME',
        'MS',
        'MA',
        'MZ',
        'MM',
        'NA',
        'NR',
        'NP',
        'NL',
        'NC',
        'NZ',
        'NI',
        'NE',
        'NG',
        'NU',
        'NF',
        'MP',
        'NO',
        'OM',
        'PK',
        'PW',
        'PS',
        'PA',
        'PG',
        'PY',
        'PE',
        'PH',
        'PN',
        'PL',
        'PT',
        'PR',
        'QA',
        'RO',
        'RU',
        'RW',
        'RE',
        'BL',
        'SH',
        'KN',
        'LC',
        'MF',
        'PM',
        'VC',
        'WS',
        'SM',
        'ST',
        'SA',
        'SN',
        'RS',
        'SC',
        'SL',
        'SG',
        'SK',
        'SI',
        'SB',
        'SO',
        'ZA',
        'SS',
        'ES',
        'LK',
        'SD',
        'SR',
        'SJ',
        'SZ',
        'SE',
        'CH',
        'SY',
        'TW',
        'TJ',
        'TZ',
        'TH',
        'TL',
        'TG',
        'TK',
        'TO',
        'TT',
        'TN',
        'TR',
        'TM',
        'TC',
        'TV',
        'UG',
        'UA',
        'AE',
        'GB',
        'US',
        'UY',
        'UZ',
        'VU',
        'VE',
        'VN',
        'VG',
        'VI',
        'WF',
        'YE',
        'ZM',
        'ZW',
      ],
      table: {
        defaultValue: {
          summary: 'FR',
        },
      },
      type: 'select',
    },
    defaultErrorMessage: {
      table: {
        defaultValue: {
          summary: 'the phone number is invalid',
        },
      },
    },
    defaultLanguage: {
      control: {
        type: 'radio',
      },
      description: 'Default language for the component',
      options: ['en', 'fr'],
      table: {
        defaultValue: {
          summary: 'en',
        },
      },
    },
    defaultOpen: {
      table: {
        defaultValue: {
          summary: false,
        },
      },
    },
    dropdownPosition: {
      table: {
        defaultValue: {
          summary: 'auto',
        },
      },
    },
    dropdownProps: {
      table: {
        defaultValue: {
          summary: '{ hasSearch: true }',
        },
      },
    },
    hasErrorOnChange: {
      table: {
        defaultValue: {
          summary: true,
        },
      },
    },
    inputPlaceholder: {
      table: {
        defaultValue: {
          summary: 'Enter your phone number',
        },
      },
    },
    inputSearchPlaceholder: {
      table: {
        defaultValue: {
          summary: 'Search a country...',
        },
      },
    },
    itemAsClickable: {
      table: {
        defaultValue: {
          summary: 'touchable-opacity',
        },
      },
    },
    language: {
      control: {
        type: 'radio',
      },
      description: 'Language for the component',
      options: ['en', 'fr'],
      table: {
        defaultValue: {
          summary: 'en',
        },
      },
    },
    maxHeight: {
      table: {
        defaultValue: {
          summary: 340,
        },
      },
    },
    minHeight: {
      table: {
        defaultValue: {
          summary: 0,
        },
      },
    },
    offsetY: {
      table: {
        defaultValue: {
          summary: 5,
        },
      },
    },
    placeholder: {
      table: {
        defaultValue: {
          summary: 'Enter your phone number',
        },
      },
    },
    searchInputProps: {
      table: {
        defaultValue: {
          summary: '{ placeholder: "Search a country..." }',
        },
      },
    },
  },
  component: PhoneNumberInput,
  decorators: [
    (Story: any) => (
      <UiPresentation>
        <Story />
      </UiPresentation>
    ),
  ],
  title: 'FORMS/PhoneNumberInput',
};

export default meta;
type Story = StoryObj<typeof PhoneNumberInput>;

// Basic PhoneNumberInput
export const Default: Story = {
  args: {},
};

export const WithDefaultCountry: Story = {
  args: {
    defaultCountry: 'FR',
    placeholder: 'Enter your phone number',
  },
};

export const WithValue: Story = {
  args: {
    defaultCountry: 'US',
    placeholder: 'Enter your phone number',
    value: '1234567890',
  },
};

// Country Restrictions
export const WithAllowedCountries: Story = {
  args: {
    allowedCountries: ['US', 'CA', 'GB', 'AU'],
    defaultCountry: 'US',
    placeholder: 'Enter your phone number',
  },
};

export const WithEuropeanCountries: Story = {
  args: {
    allowedCountries: ['FR', 'DE', 'IT', 'ES', 'GB', 'NL', 'BE'],
    defaultCountry: 'FR',
    placeholder: 'Enter your phone number',
  },
};

// Language Support
export const FrenchLanguage: Story = {
  args: {
    defaultCountry: 'FR',
    language: 'fr',
    placeholder: 'Entrez votre numéro de téléphone',
  },
};

// Validation Examples
export const WithValidation: Story = {
  args: {
    defaultCountry: 'US',
    errorMessage: 'Please enter a valid phone number',
    hasErrorOnChange: true,
    placeholder: 'Enter your phone number',
  },
};

export const WithCustomErrorMessage: Story = {
  args: {
    defaultCountry: 'FR',
    errorMessage: 'Veuillez entrer un numéro de téléphone valide',
    hasErrorOnChange: true,
    language: 'fr',
    placeholder: 'Entrez votre numéro de téléphone',
  },
};
