import { PhoneNumberInputCountryCodesProps } from '@types';

export const countryCodes: PhoneNumberInputCountryCodesProps[] = [
  {
    code: 'AF',
    dial_code: '+93',
    en: 'Afghanistan',
    fr: 'Afghanistan',
    id: 'AF',
  },
  {
    code: 'AX',
    dial_code: '+358',
    en: 'Aland Islands',
    fr: 'Îles Åland',
    id: 'AX',
  },
  {
    code: 'AL',
    dial_code: '+355',
    en: 'Albania',
    fr: 'Albanie',
    id: 'AL',
  },
  {
    code: 'DZ',
    dial_code: '+213',
    en: 'Algeria',
    fr: 'Algérie',
    id: 'DZ',
  },
  {
    code: 'AS',
    dial_code: '+1684',
    en: 'American Samoa',
    fr: 'Samoa américaines',
    id: 'AS',
  },
  {
    code: 'AD',
    dial_code: '+376',
    en: 'Andorra',
    fr: 'Andorre',
    id: 'AD',
  },
  {
    code: 'AO',
    dial_code: '+244',
    en: 'Angola',
    fr: 'Angola',
    id: 'AO',
  },
  {
    code: 'AI',
    dial_code: '+1264',
    en: 'Anguilla',
    fr: 'Anguilla',
    id: 'AI',
  },
  {
    code: 'AQ',
    dial_code: '+672',
    en: 'Antarctica',
    fr: 'Antarctique',
    id: 'AQ',
  },
  {
    code: 'AG',
    dial_code: '+1268',
    en: 'Antigua and Barbuda',
    fr: 'Antigua-et-Barbuda',
    id: 'AG',
  },
  {
    code: 'AR',
    dial_code: '+54',
    en: 'Argentina',
    fr: 'Argentine',
    id: 'AR',
  },
  {
    code: 'AM',
    dial_code: '+374',
    en: 'Armenia',
    fr: 'Arménie',
    id: 'AM',
  },
  {
    code: 'AW',
    dial_code: '+297',
    en: 'Aruba',
    fr: 'Aruba',
    id: 'AW',
  },
  {
    code: 'AU',
    dial_code: '+61',
    en: 'Australia',
    fr: 'Australie',
    id: 'AU',
  },
  {
    code: 'AT',
    dial_code: '+43',
    en: 'Austria',
    fr: 'Autriche',
    id: 'AT',
  },
  {
    code: 'AZ',
    dial_code: '+994',
    en: 'Azerbaijan',
    fr: 'Azerbaïdjan',
    id: 'AZ',
  },
  {
    code: 'BS',
    dial_code: '+1242',
    en: 'Bahamas',
    fr: 'Bahamas',
    id: 'BS',
  },
  {
    code: 'BH',
    dial_code: '+973',
    en: 'Bahrain',
    fr: 'Bahreïn',
    id: 'BH',
  },
  {
    code: 'BD',
    dial_code: '+880',
    en: 'Bangladesh',
    fr: 'Bangladesh',
    id: 'BD',
  },
  {
    code: 'BB',
    dial_code: '+1246',
    en: 'Barbados',
    fr: 'Barbade',
    id: 'BB',
  },
  {
    code: 'BY',
    dial_code: '+375',
    en: 'Belarus',
    fr: 'Biélorussie',
    id: 'BY',
  },
  {
    code: 'BE',
    dial_code: '+32',
    en: 'Belgium',
    fr: 'Belgique',
    id: 'BE',
  },
  {
    code: 'BZ',
    dial_code: '+501',
    en: 'Belize',
    fr: 'Belize',
    id: 'BZ',
  },
  {
    code: 'BJ',
    dial_code: '+229',
    en: 'Benin',
    fr: 'Bénin',
    id: 'BJ',
  },
  {
    code: 'BM',
    dial_code: '+1441',
    en: 'Bermuda',
    fr: 'Bermudes',
    id: 'BM',
  },
  {
    code: 'BT',
    dial_code: '+975',
    en: 'Bhutan',
    fr: 'Bhoutan',
    id: 'BT',
  },
  {
    code: 'BO',
    dial_code: '+591',
    en: 'Bolivia',
    fr: 'Bolivie',
    id: 'BO',
  },
  {
    code: 'BA',
    dial_code: '+387',
    en: 'Bosnia and Herzegovina',
    fr: 'Bosnie-Herzégovine',
    id: 'BA',
  },
  {
    code: 'BW',
    dial_code: '+267',
    en: 'Botswana',
    fr: 'Botswana',
    id: 'BW',
  },
  {
    code: 'BR',
    dial_code: '+55',
    en: 'Brazil',
    fr: 'Brésil',
    id: 'BR',
  },
  {
    code: 'IO',
    dial_code: '+246',
    en: 'British Indian Ocean Territory',
    fr: "Territoire britannique de l'océan Indien",
    id: 'IO',
  },
  {
    code: 'BN',
    dial_code: '+673',
    en: 'Brunei',
    fr: 'Brunei',
    id: 'BN',
  },
  {
    code: 'BG',
    dial_code: '+359',
    en: 'Bulgaria',
    fr: 'Bulgarie',
    id: 'BG',
  },
  {
    code: 'BF',
    dial_code: '+226',
    en: 'Burkina Faso',
    fr: 'Burkina Faso',
    id: 'BF',
  },
  {
    code: 'BI',
    dial_code: '+257',
    en: 'Burundi',
    fr: 'Burundi',
    id: 'BI',
  },
  {
    code: 'KH',
    dial_code: '+855',
    en: 'Cambodia',
    fr: 'Cambodge',
    id: 'KH',
  },
  {
    code: 'CM',
    dial_code: '+237',
    en: 'Cameroon',
    fr: 'Cameroun',
    id: 'CM',
  },
  {
    code: 'CA',
    dial_code: '+1',
    en: 'Canada',
    fr: 'Canada',
    id: 'CA',
  },
  {
    code: 'CV',
    dial_code: '+238',
    en: 'Cape Verde',
    fr: 'Cap-Vert',
    id: 'CV',
  },
  {
    code: 'KY',
    dial_code: '+345',
    en: 'Cayman Islands',
    fr: 'Îles Caïmans',
    id: 'KY',
  },
  {
    code: 'CF',
    dial_code: '+236',
    en: 'Central African Republic',
    fr: 'République centrafricaine',
    id: 'CF',
  },
  {
    code: 'TD',
    dial_code: '+235',
    en: 'Chad',
    fr: 'Tchad',
    id: 'TD',
  },
  {
    code: 'CL',
    dial_code: '+56',
    en: 'Chile',
    fr: 'Chili',
    id: 'CL',
  },
  {
    code: 'CN',
    dial_code: '+86',
    en: 'China',
    fr: 'Chine',
    id: 'CN',
  },
  {
    code: 'CX',
    dial_code: '+61',
    en: 'Christmas Island',
    fr: 'Île Christmas',
    id: 'CX',
  },
  {
    code: 'CC',
    dial_code: '+61',
    en: 'Cocos (Keeling) Islands',
    fr: 'Îles Cocos',
    id: 'CC',
  },
  {
    code: 'CO',
    dial_code: '+57',
    en: 'Colombia',
    fr: 'Colombie',
    id: 'CO',
  },
  {
    code: 'KM',
    dial_code: '+269',
    en: 'Comoros',
    fr: 'Comores',
    id: 'KM',
  },
  {
    code: 'CG',
    dial_code: '+242',
    en: 'Congo',
    fr: 'Congo',
    id: 'CG',
  },
  {
    code: 'CD',
    dial_code: '+243',
    en: 'Democratic Republic of the Congo',
    fr: 'République démocratique du Congo',
    id: 'CD',
  },
  {
    code: 'CK',
    dial_code: '+682',
    en: 'Cook Islands',
    fr: 'Îles Cook',
    id: 'CK',
  },
  {
    code: 'CR',
    dial_code: '+506',
    en: 'Costa Rica',
    fr: 'Costa Rica',
    id: 'CR',
  },
  {
    code: 'CI',
    dial_code: '+225',
    en: 'Ivory Coast',
    fr: "Côte d'Ivoire",
    id: 'CI',
  },
  {
    code: 'HR',
    dial_code: '+385',
    en: 'Croatia',
    fr: 'Croatie',
    id: 'HR',
  },
  {
    code: 'CU',
    dial_code: '+53',
    en: 'Cuba',
    fr: 'Cuba',
    id: 'CU',
  },
  {
    code: 'CY',
    dial_code: '+357',
    en: 'Cyprus',
    fr: 'Chypre',
    id: 'CY',
  },
  {
    code: 'CZ',
    dial_code: '+420',
    en: 'Czech Republic',
    fr: 'République tchèque',
    id: 'CZ',
  },
  {
    code: 'DK',
    dial_code: '+45',
    en: 'Denmark',
    fr: 'Danemark',
    id: 'DK',
  },
  {
    code: 'DJ',
    dial_code: '+253',
    en: 'Djibouti',
    fr: 'Djibouti',
    id: 'DJ',
  },
  {
    code: 'DM',
    dial_code: '+1767',
    en: 'Dominica',
    fr: 'Dominique',
    id: 'DM',
  },
  {
    code: 'DO',
    dial_code: '+1849',
    en: 'Dominican Republic',
    fr: 'République dominicaine',
    id: 'DO',
  },
  {
    code: 'EC',
    dial_code: '+593',
    en: 'Ecuador',
    fr: 'Équateur',
    id: 'EC',
  },
  {
    code: 'EG',
    dial_code: '+20',
    en: 'Egypt',
    fr: 'Égypte',
    id: 'EG',
  },
  {
    code: 'SV',
    dial_code: '+503',
    en: 'El Salvador',
    fr: 'El Salvador',
    id: 'SV',
  },
  {
    code: 'GQ',
    dial_code: '+240',
    en: 'Equatorial Guinea',
    fr: 'Guinée équatoriale',
    id: 'GQ',
  },
  {
    code: 'ER',
    dial_code: '+291',
    en: 'Eritrea',
    fr: 'Érythrée',
    id: 'ER',
  },
  {
    code: 'EE',
    dial_code: '+372',
    en: 'Estonia',
    fr: 'Estonie',
    id: 'EE',
  },
  {
    code: 'ET',
    dial_code: '+251',
    en: 'Ethiopia',
    fr: 'Éthiopie',
    id: 'ET',
  },
  {
    code: 'FK',
    dial_code: '+500',
    en: 'Falkland Islands',
    fr: 'Îles Malouines',
    id: 'FK',
  },
  {
    code: 'FO',
    dial_code: '+298',
    en: 'Faroe Islands',
    fr: 'Îles Féroé',
    id: 'FO',
  },
  {
    code: 'FJ',
    dial_code: '+679',
    en: 'Fiji',
    fr: 'Fidji',
    id: 'FJ',
  },
  {
    code: 'FI',
    dial_code: '+358',
    en: 'Finland',
    fr: 'Finlande',
    id: 'FI',
  },
  {
    code: 'FR',
    dial_code: '+33',
    en: 'France',
    fr: 'France',
    id: 'FR',
  },
  {
    code: 'GF',
    dial_code: '+594',
    en: 'French Guiana',
    fr: 'Guyane française',
    id: 'GF',
  },
  {
    code: 'PF',
    dial_code: '+689',
    en: 'French Polynesia',
    fr: 'Polynésie française',
    id: 'PF',
  },
  {
    code: 'GA',
    dial_code: '+241',
    en: 'Gabon',
    fr: 'Gabon',
    id: 'GA',
  },
  {
    code: 'GM',
    dial_code: '+220',
    en: 'Gambia',
    fr: 'Gambie',
    id: 'GM',
  },
  {
    code: 'GE',
    dial_code: '+995',
    en: 'Georgia',
    fr: 'Géorgie',
    id: 'GE',
  },
  {
    code: 'DE',
    dial_code: '+49',
    en: 'Germany',
    fr: 'Allemagne',
    id: 'DE',
  },
  {
    code: 'GH',
    dial_code: '+233',
    en: 'Ghana',
    fr: 'Ghana',
    id: 'GH',
  },
  {
    code: 'GI',
    dial_code: '+350',
    en: 'Gibraltar',
    fr: 'Gibraltar',
    id: 'GI',
  },
  {
    code: 'GR',
    dial_code: '+30',
    en: 'Greece',
    fr: 'Grèce',
    id: 'GR',
  },
  {
    code: 'GL',
    dial_code: '+299',
    en: 'Greenland',
    fr: 'Groenland',
    id: 'GL',
  },
  {
    code: 'GD',
    dial_code: '+1473',
    en: 'Grenada',
    fr: 'Grenade',
    id: 'GD',
  },
  {
    code: 'GP',
    dial_code: '+590',
    en: 'Guadeloupe',
    fr: 'Guadeloupe',
    id: 'GP',
  },
  {
    code: 'GU',
    dial_code: '+1671',
    en: 'Guam',
    fr: 'Guam',
    id: 'GU',
  },
  {
    code: 'GT',
    dial_code: '+502',
    en: 'Guatemala',
    fr: 'Guatemala',
    id: 'GT',
  },
  {
    code: 'GG',
    dial_code: '+44',
    en: 'Guernsey',
    fr: 'Guernesey',
    id: 'GG',
  },
  {
    code: 'GN',
    dial_code: '+224',
    en: 'Guinea',
    fr: 'Guinée',
    id: 'GN',
  },
  {
    code: 'GW',
    dial_code: '+245',
    en: 'Guinea-Bissau',
    fr: 'Guinée-Bissau',
    id: 'GW',
  },
  {
    code: 'GY',
    dial_code: '+595',
    en: 'Guyana',
    fr: 'Guyana',
    id: 'GY',
  },
  {
    code: 'HT',
    dial_code: '+509',
    en: 'Haiti',
    fr: 'Haïti',
    id: 'HT',
  },
  {
    code: 'VA',
    dial_code: '+379',
    en: 'Vatican City',
    fr: 'Vatican',
    id: 'VA',
  },
  {
    code: 'HN',
    dial_code: '+504',
    en: 'Honduras',
    fr: 'Honduras',
    id: 'HN',
  },
  {
    code: 'HK',
    dial_code: '+852',
    en: 'Hong Kong',
    fr: 'Hong Kong',
    id: 'HK',
  },
  {
    code: 'HU',
    dial_code: '+36',
    en: 'Hungary',
    fr: 'Hongrie',
    id: 'HU',
  },
  {
    code: 'IS',
    dial_code: '+354',
    en: 'Iceland',
    fr: 'Islande',
    id: 'IS',
  },
  {
    code: 'IN',
    dial_code: '+91',
    en: 'India',
    fr: 'Inde',
    id: 'IN',
  },
  {
    code: 'ID',
    dial_code: '+62',
    en: 'Indonesia',
    fr: 'Indonésie',
    id: 'ID',
  },
  {
    code: 'IR',
    dial_code: '+98',
    en: 'Iran',
    fr: 'Iran',
    id: 'IR',
  },
  {
    code: 'IQ',
    dial_code: '+964',
    en: 'Iraq',
    fr: 'Irak',
    id: 'IQ',
  },
  {
    code: 'IE',
    dial_code: '+353',
    en: 'Ireland',
    fr: 'Irlande',
    id: 'IE',
  },
  {
    code: 'IM',
    dial_code: '+44',
    en: 'Isle of Man',
    fr: 'Île de Man',
    id: 'IM',
  },
  {
    code: 'IL',
    dial_code: '+972',
    en: 'Israel',
    fr: 'Israël',
    id: 'IL',
  },
  {
    code: 'IT',
    dial_code: '+39',
    en: 'Italy',
    fr: 'Italie',
    id: 'IT',
  },
  {
    code: 'JM',
    dial_code: '+1876',
    en: 'Jamaica',
    fr: 'Jamaïque',
    id: 'JM',
  },
  {
    code: 'JP',
    dial_code: '+81',
    en: 'Japan',
    fr: 'Japon',
    id: 'JP',
  },
  {
    code: 'JE',
    dial_code: '+44',
    en: 'Jersey',
    fr: 'Jersey',
    id: 'JE',
  },
  {
    code: 'JO',
    dial_code: '+962',
    en: 'Jordan',
    fr: 'Jordanie',
    id: 'JO',
  },
  {
    code: 'KZ',
    dial_code: '+77',
    en: 'Kazakhstan',
    fr: 'Kazakhstan',
    id: 'KZ',
  },
  {
    code: 'KE',
    dial_code: '+254',
    en: 'Kenya',
    fr: 'Kenya',
    id: 'KE',
  },
  {
    code: 'KI',
    dial_code: '+686',
    en: 'Kiribati',
    fr: 'Kiribati',
    id: 'KI',
  },
  {
    code: 'KP',
    dial_code: '+850',
    en: 'North Korea',
    fr: 'Corée du Nord',
    id: 'KP',
  },
  {
    code: 'KR',
    dial_code: '+82',
    en: 'South Korea',
    fr: 'Corée du Sud',
    id: 'KR',
  },
  {
    code: 'KW',
    dial_code: '+965',
    en: 'Kuwait',
    fr: 'Koweït',
    id: 'KW',
  },
  {
    code: 'KG',
    dial_code: '+996',
    en: 'Kyrgyzstan',
    fr: 'Kirghizistan',
    id: 'KG',
  },
  {
    code: 'LA',
    dial_code: '+856',
    en: 'Laos',
    fr: 'Laos',
    id: 'LA',
  },
  {
    code: 'LV',
    dial_code: '+371',
    en: 'Latvia',
    fr: 'Lettonie',
    id: 'LV',
  },
  {
    code: 'LB',
    dial_code: '+961',
    en: 'Lebanon',
    fr: 'Liban',
    id: 'LB',
  },
  {
    code: 'LS',
    dial_code: '+266',
    en: 'Lesotho',
    fr: 'Lesotho',
    id: 'LS',
  },
  {
    code: 'LR',
    dial_code: '+231',
    en: 'Liberia',
    fr: 'Libéria',
    id: 'LR',
  },
  {
    code: 'LY',
    dial_code: '+218',
    en: 'Libya',
    fr: 'Libye',
    id: 'LY',
  },
  {
    code: 'LI',
    dial_code: '+423',
    en: 'Liechtenstein',
    fr: 'Liechtenstein',
    id: 'LI',
  },
  {
    code: 'LT',
    dial_code: '+370',
    en: 'Lithuania',
    fr: 'Lituanie',
    id: 'LT',
  },
  {
    code: 'LU',
    dial_code: '+352',
    en: 'Luxembourg',
    fr: 'Luxembourg',
    id: 'LU',
  },
  {
    code: 'MO',
    dial_code: '+853',
    en: 'Macao',
    fr: 'Macao',
    id: 'MO',
  },
  {
    code: 'MK',
    dial_code: '+389',
    en: 'North Macedonia',
    fr: 'Macédoine du Nord',
    id: 'MK',
  },
  {
    code: 'MG',
    dial_code: '+261',
    en: 'Madagascar',
    fr: 'Madagascar',
    id: 'MG',
  },
  {
    code: 'MW',
    dial_code: '+265',
    en: 'Malawi',
    fr: 'Malawi',
    id: 'MW',
  },
  {
    code: 'MY',
    dial_code: '+60',
    en: 'Malaysia',
    fr: 'Malaisie',
    id: 'MY',
  },
  {
    code: 'MV',
    dial_code: '+960',
    en: 'Maldives',
    fr: 'Maldives',
    id: 'MV',
  },
  {
    code: 'ML',
    dial_code: '+223',
    en: 'Mali',
    fr: 'Mali',
    id: 'ML',
  },
  {
    code: 'MT',
    dial_code: '+356',
    en: 'Malta',
    fr: 'Malte',
    id: 'MT',
  },
  {
    code: 'MH',
    dial_code: '+692',
    en: 'Marshall Islands',
    fr: 'Îles Marshall',
    id: 'MH',
  },
  {
    code: 'MQ',
    dial_code: '+596',
    en: 'Martinique',
    fr: 'Martinique',
    id: 'MQ',
  },
  {
    code: 'MR',
    dial_code: '+222',
    en: 'Mauritania',
    fr: 'Mauritanie',
    id: 'MR',
  },
  {
    code: 'MU',
    dial_code: '+230',
    en: 'Mauritius',
    fr: 'Maurice',
    id: 'MU',
  },
  {
    code: 'YT',
    dial_code: '+262',
    en: 'Mayotte',
    fr: 'Mayotte',
    id: 'YT',
  },
  {
    code: 'MX',
    dial_code: '+52',
    en: 'Mexico',
    fr: 'Mexique',
    id: 'MX',
  },
  {
    code: 'FM',
    dial_code: '+691',
    en: 'Micronesia',
    fr: 'Micronésie',
    id: 'FM',
  },
  {
    code: 'MD',
    dial_code: '+373',
    en: 'Moldova',
    fr: 'Moldavie',
    id: 'MD',
  },
  {
    code: 'MC',
    dial_code: '+377',
    en: 'Monaco',
    fr: 'Monaco',
    id: 'MC',
  },
  {
    code: 'MN',
    dial_code: '+976',
    en: 'Mongolia',
    fr: 'Mongolie',
    id: 'MN',
  },
  {
    code: 'ME',
    dial_code: '+382',
    en: 'Montenegro',
    fr: 'Monténégro',
    id: 'ME',
  },
  {
    code: 'MS',
    dial_code: '+1664',
    en: 'Montserrat',
    fr: 'Montserrat',
    id: 'MS',
  },
  {
    code: 'MA',
    dial_code: '+212',
    en: 'Morocco',
    fr: 'Maroc',
    id: 'MA',
  },
  {
    code: 'MZ',
    dial_code: '+258',
    en: 'Mozambique',
    fr: 'Mozambique',
    id: 'MZ',
  },
  {
    code: 'MM',
    dial_code: '+95',
    en: 'Myanmar',
    fr: 'Myanmar',
    id: 'MM',
  },
  {
    code: 'NA',
    dial_code: '+264',
    en: 'Namibia',
    fr: 'Namibie',
    id: 'NA',
  },
  {
    code: 'NR',
    dial_code: '+674',
    en: 'Nauru',
    fr: 'Nauru',
    id: 'NR',
  },
  {
    code: 'NP',
    dial_code: '+977',
    en: 'Nepal',
    fr: 'Népal',
    id: 'NP',
  },
  {
    code: 'NL',
    dial_code: '+31',
    en: 'Netherlands',
    fr: 'Pays-Bas',
    id: 'NL',
  },
  {
    code: 'NC',
    dial_code: '+687',
    en: 'New Caledonia',
    fr: 'Nouvelle-Calédonie',
    id: 'NC',
  },
  {
    code: 'NZ',
    dial_code: '+64',
    en: 'New Zealand',
    fr: 'Nouvelle-Zélande',
    id: 'NZ',
  },
  {
    code: 'NI',
    dial_code: '+505',
    en: 'Nicaragua',
    fr: 'Nicaragua',
    id: 'NI',
  },
  {
    code: 'NE',
    dial_code: '+227',
    en: 'Niger',
    fr: 'Niger',
    id: 'NE',
  },
  {
    code: 'NG',
    dial_code: '+234',
    en: 'Nigeria',
    fr: 'Nigeria',
    id: 'NG',
  },
  {
    code: 'NU',
    dial_code: '+683',
    en: 'Niue',
    fr: 'Niue',
    id: 'NU',
  },
  {
    code: 'NF',
    dial_code: '+672',
    en: 'Norfolk Island',
    fr: 'Île Norfolk',
    id: 'NF',
  },
  {
    code: 'MP',
    dial_code: '+1670',
    en: 'Northern Mariana Islands',
    fr: 'Îles Mariannes du Nord',
    id: 'MP',
  },
  {
    code: 'NO',
    dial_code: '+47',
    en: 'Norway',
    fr: 'Norvège',
    id: 'NO',
  },
  {
    code: 'OM',
    dial_code: '+968',
    en: 'Oman',
    fr: 'Oman',
    id: 'OM',
  },
  {
    code: 'PK',
    dial_code: '+92',
    en: 'Pakistan',
    fr: 'Pakistan',
    id: 'PK',
  },
  {
    code: 'PW',
    dial_code: '+680',
    en: 'Palau',
    fr: 'Palaos',
    id: 'PW',
  },
  {
    code: 'PS',
    dial_code: '+970',
    en: 'Palestine',
    fr: 'Palestine',
    id: 'PS',
  },
  {
    code: 'PA',
    dial_code: '+507',
    en: 'Panama',
    fr: 'Panama',
    id: 'PA',
  },
  {
    code: 'PG',
    dial_code: '+675',
    en: 'Papua New Guinea',
    fr: 'Papouasie-Nouvelle-Guinée',
    id: 'PG',
  },
  {
    code: 'PY',
    dial_code: '+595',
    en: 'Paraguay',
    fr: 'Paraguay',
    id: 'PY',
  },
  {
    code: 'PE',
    dial_code: '+51',
    en: 'Peru',
    fr: 'Pérou',
    id: 'PE',
  },
  {
    code: 'PH',
    dial_code: '+63',
    en: 'Philippines',
    fr: 'Philippines',
    id: 'PH',
  },
  {
    code: 'PN',
    dial_code: '+872',
    en: 'Pitcairn',
    fr: 'Îles Pitcairn',
    id: 'PN',
  },
  {
    code: 'PL',
    dial_code: '+48',
    en: 'Poland',
    fr: 'Pologne',
    id: 'PL',
  },
  {
    code: 'PT',
    dial_code: '+351',
    en: 'Portugal',
    fr: 'Portugal',
    id: 'PT',
  },
  {
    code: 'PR',
    dial_code: '+1939',
    en: 'Puerto Rico',
    fr: 'Porto Rico',
    id: 'PR',
  },
  {
    code: 'QA',
    dial_code: '+974',
    en: 'Qatar',
    fr: 'Qatar',
    id: 'QA',
  },
  {
    code: 'RO',
    dial_code: '+40',
    en: 'Romania',
    fr: 'Roumanie',
    id: 'RO',
  },
  {
    code: 'RU',
    dial_code: '+7',
    en: 'Russia',
    fr: 'Russie',
    id: 'RU',
  },
  {
    code: 'RW',
    dial_code: '+250',
    en: 'Rwanda',
    fr: 'Rwanda',
    id: 'RW',
  },
  {
    code: 'RE',
    dial_code: '+262',
    en: 'Reunion',
    fr: 'La Réunion',
    id: 'RE',
  },
  {
    code: 'BL',
    dial_code: '+590',
    en: 'Saint Barthelemy',
    fr: 'Saint-Barthélemy',
    id: 'BL',
  },
  {
    code: 'SH',
    dial_code: '+290',
    en: 'Saint Helena',
    fr: 'Sainte-Hélène',
    id: 'SH',
  },
  {
    code: 'KN',
    dial_code: '+1869',
    en: 'Saint Kitts and Nevis',
    fr: 'Saint-Kitts-et-Nevis',
    id: 'KN',
  },
  {
    code: 'LC',
    dial_code: '+1758',
    en: 'Saint Lucia',
    fr: 'Sainte-Lucie',
    id: 'LC',
  },
  {
    code: 'MF',
    dial_code: '+590',
    en: 'Saint Martin',
    fr: 'Saint-Martin',
    id: 'MF',
  },
  {
    code: 'PM',
    dial_code: '+508',
    en: 'Saint Pierre and Miquelon',
    fr: 'Saint-Pierre-et-Miquelon',
    id: 'PM',
  },
  {
    code: 'VC',
    dial_code: '+1784',
    en: 'Saint Vincent and the Grenadines',
    fr: 'Saint-Vincent-et-les-Grenadines',
    id: 'VC',
  },
  {
    code: 'WS',
    dial_code: '+685',
    en: 'Samoa',
    fr: 'Samoa',
    id: 'WS',
  },
  {
    code: 'SM',
    dial_code: '+378',
    en: 'San Marino',
    fr: 'Saint-Marin',
    id: 'SM',
  },
  {
    code: 'ST',
    dial_code: '+239',
    en: 'Sao Tome and Principe',
    fr: 'Sao Tomé-et-Principe',
    id: 'ST',
  },
  {
    code: 'SA',
    dial_code: '+966',
    en: 'Saudi Arabia',
    fr: 'Arabie saoudite',
    id: 'SA',
  },
  {
    code: 'SN',
    dial_code: '+221',
    en: 'Senegal',
    fr: 'Sénégal',
    id: 'SN',
  },
  {
    code: 'RS',
    dial_code: '+381',
    en: 'Serbia',
    fr: 'Serbie',
    id: 'RS',
  },
  {
    code: 'SC',
    dial_code: '+248',
    en: 'Seychelles',
    fr: 'Seychelles',
    id: 'SC',
  },
  {
    code: 'SL',
    dial_code: '+232',
    en: 'Sierra Leone',
    fr: 'Sierra Leone',
    id: 'SL',
  },
  {
    code: 'SG',
    dial_code: '+65',
    en: 'Singapore',
    fr: 'Singapour',
    id: 'SG',
  },
  {
    code: 'SK',
    dial_code: '+421',
    en: 'Slovakia',
    fr: 'Slovaquie',
    id: 'SK',
  },
  {
    code: 'SI',
    dial_code: '+386',
    en: 'Slovenia',
    fr: 'Slovénie',
    id: 'SI',
  },
  {
    code: 'SB',
    dial_code: '+677',
    en: 'Solomon Islands',
    fr: 'Îles Salomon',
    id: 'SB',
  },
  {
    code: 'SO',
    dial_code: '+252',
    en: 'Somalia',
    fr: 'Somalie',
    id: 'SO',
  },
  {
    code: 'ZA',
    dial_code: '+27',
    en: 'South Africa',
    fr: 'Afrique du Sud',
    id: 'ZA',
  },
  {
    code: 'SS',
    dial_code: '+211',
    en: 'South Sudan',
    fr: 'Soudan du Sud',
    id: 'SS',
  },
  {
    code: 'ES',
    dial_code: '+34',
    en: 'Spain',
    fr: 'Espagne',
    id: 'ES',
  },
  {
    code: 'LK',
    dial_code: '+94',
    en: 'Sri Lanka',
    fr: 'Sri Lanka',
    id: 'LK',
  },
  {
    code: 'SD',
    dial_code: '+249',
    en: 'Sudan',
    fr: 'Soudan',
    id: 'SD',
  },
  {
    code: 'SR',
    dial_code: '+597',
    en: 'Suriname',
    fr: 'Suriname',
    id: 'SR',
  },
  {
    code: 'SJ',
    dial_code: '+47',
    en: 'Svalbard and Jan Mayen',
    fr: 'Svalbard et Jan Mayen',
    id: 'SJ',
  },
  {
    code: 'SZ',
    dial_code: '+268',
    en: 'Eswatini',
    fr: 'Eswatini',
    id: 'SZ',
  },
  {
    code: 'SE',
    dial_code: '+46',
    en: 'Sweden',
    fr: 'Suède',
    id: 'SE',
  },
  {
    code: 'CH',
    dial_code: '+41',
    en: 'Switzerland',
    fr: 'Suisse',
    id: 'CH',
  },
  {
    code: 'SY',
    dial_code: '+963',
    en: 'Syria',
    fr: 'Syrie',
    id: 'SY',
  },
  {
    code: 'TW',
    dial_code: '+886',
    en: 'Taiwan',
    fr: 'Taïwan',
    id: 'TW',
  },
  {
    code: 'TJ',
    dial_code: '+992',
    en: 'Tajikistan',
    fr: 'Tadjikistan',
    id: 'TJ',
  },
  {
    code: 'TZ',
    dial_code: '+255',
    en: 'Tanzania',
    fr: 'Tanzanie',
    id: 'TZ',
  },
  {
    code: 'TH',
    dial_code: '+66',
    en: 'Thailand',
    fr: 'Thaïlande',
    id: 'TH',
  },
  {
    code: 'TL',
    dial_code: '+670',
    en: 'Timor-Leste',
    fr: 'Timor oriental',
    id: 'TL',
  },
  {
    code: 'TG',
    dial_code: '+228',
    en: 'Togo',
    fr: 'Togo',
    id: 'TG',
  },
  {
    code: 'TK',
    dial_code: '+690',
    en: 'Tokelau',
    fr: 'Tokelau',
    id: 'TK',
  },
  {
    code: 'TO',
    dial_code: '+676',
    en: 'Tonga',
    fr: 'Tonga',
    id: 'TO',
  },
  {
    code: 'TT',
    dial_code: '+1868',
    en: 'Trinidad and Tobago',
    fr: 'Trinité-et-Tobago',
    id: 'TT',
  },
  {
    code: 'TN',
    dial_code: '+216',
    en: 'Tunisia',
    fr: 'Tunisie',
    id: 'TN',
  },
  {
    code: 'TR',
    dial_code: '+90',
    en: 'Turkey',
    fr: 'Turquie',
    id: 'TR',
  },
  {
    code: 'TM',
    dial_code: '+993',
    en: 'Turkmenistan',
    fr: 'Turkménistan',
    id: 'TM',
  },
  {
    code: 'TC',
    dial_code: '+1649',
    en: 'Turks and Caicos Islands',
    fr: 'Îles Turques-et-Caïques',
    id: 'TC',
  },
  {
    code: 'TV',
    dial_code: '+688',
    en: 'Tuvalu',
    fr: 'Tuvalu',
    id: 'TV',
  },
  {
    code: 'UG',
    dial_code: '+256',
    en: 'Uganda',
    fr: 'Ouganda',
    id: 'UG',
  },
  {
    code: 'UA',
    dial_code: '+380',
    en: 'Ukraine',
    fr: 'Ukraine',
    id: 'UA',
  },
  {
    code: 'AE',
    dial_code: '+971',
    en: 'United Arab Emirates',
    fr: 'Émirats arabes unis',
    id: 'AE',
  },
  {
    code: 'GB',
    dial_code: '+44',
    en: 'United Kingdom',
    fr: 'Royaume-Uni',
    id: 'GB',
  },
  {
    code: 'US',
    dial_code: '+1',
    en: 'United States',
    fr: 'États-Unis',
    id: 'US',
  },
  {
    code: 'UY',
    dial_code: '+598',
    en: 'Uruguay',
    fr: 'Uruguay',
    id: 'UY',
  },
  {
    code: 'UZ',
    dial_code: '+998',
    en: 'Uzbekistan',
    fr: 'Ouzbékistan',
    id: 'UZ',
  },
  {
    code: 'VU',
    dial_code: '+678',
    en: 'Vanuatu',
    fr: 'Vanuatu',
    id: 'VU',
  },
  {
    code: 'VE',
    dial_code: '+58',
    en: 'Venezuela',
    fr: 'Venezuela',
    id: 'VE',
  },
  {
    code: 'VN',
    dial_code: '+84',
    en: 'Vietnam',
    fr: 'Vietnam',
    id: 'VN',
  },
  {
    code: 'VG',
    dial_code: '+1284',
    en: 'British Virgin Islands',
    fr: 'Îles Vierges britanniques',
    id: 'VG',
  },
  {
    code: 'VI',
    dial_code: '+1340',
    en: 'U.S. Virgin Islands',
    fr: 'Îles Vierges des États-Unis',
    id: 'VI',
  },
  {
    code: 'WF',
    dial_code: '+681',
    en: 'Wallis and Futuna',
    fr: 'Wallis-et-Futuna',
    id: 'WF',
  },
  {
    code: 'YE',
    dial_code: '+967',
    en: 'Yemen',
    fr: 'Yémen',
    id: 'YE',
  },
  {
    code: 'ZM',
    dial_code: '+260',
    en: 'Zambia',
    fr: 'Zambie',
    id: 'ZM',
  },
  {
    code: 'ZW',
    dial_code: '+263',
    en: 'Zimbabwe',
    fr: 'Zimbabwe',
    id: 'ZW',
  },
];
