/* do not change this file, it is auto generated by storybook. */

import { start, updateView } from '@storybook/react-native';

import '@storybook/addon-ondevice-controls/register';
import '@storybook/addon-ondevice-actions/register';
import '@storybook/addon-ondevice-notes/register';

const normalizedStories = [
  {
    titlePrefix: '',
    directory: './stories',
    files: '**/*.stories.?(ts|tsx|js|jsx)',
    importPathMatcher: /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx|js|jsx)?)$/,
    // @ts-ignore
    req: require.context(
      '../stories',
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx|js|jsx)?)$/,
    ),
  },
];

// @ts-ignore
module?.hot?.accept?.();

if (!global.view) {
  global.view = start({
    annotations: [
      require('./preview'),
      require('@storybook/react-native/preview'),
      require('@storybook/addon-ondevice-actions/preview'),
    ],
    storyEntries: normalizedStories,
  });
} else {
  updateView(
    global.view,
    [
      require('./preview'),
      require('@storybook/react-native/preview'),
      require('@storybook/addon-ondevice-actions/preview'),
    ],
    normalizedStories,
  );
}

export const view = global.view;
